StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{62CD5334BF7A961C}" {
   Id "BritishMalaya"
   Target_en_us "British Malaya"
   Target_en_us_edited ""
   Target_fr_fr "Malaisie britannique"
   Target_it_it "Malaysia britannica"
   Target_de_de "Britisch Malaya"
   Target_es_es "Malasia británica"
   Target_cs_cz "Britská Malajsie"
   Target_pl_pl "Brytyjska Malaja"
   Target_ru_ru "Британская Малайя"
   Target_ja_jp "イギリス領マラヤ"
   Target_ko_kr "영국 말라야"
   Target_pt_br "Malásia Britânica"
   Target_zh_cn "英属马来亚"
   Target_uk_ua "Британська Малая"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334B2809F00}" {
   Id "BritishRaj"
   Target_en_us "British Raj"
   Target_en_us_edited ""
   Target_fr_fr "Raj britannique"
   Target_it_it "Raj britannico"
   Target_de_de "Britisches Indien"
   Target_es_es "Raj británico"
   Target_cs_cz "Britská Indie"
   Target_pl_pl "Brytyjski Radż"
   Target_ru_ru "Британский Радж"
   Target_ja_jp "イギリス領インド"
   Target_ko_kr "영국령 인도"
   Target_pt_br "Raj Britânico"
   Target_zh_cn "英属印度"
   Target_uk_ua "Британський Радж"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334A0593E96}" {
   Id "Canadian1801"
   Target_en_us "Canadian 1801"
   Target_en_us_edited ""
   Target_fr_fr "Canadien 1801"
   Target_it_it "Canadese 1801"
   Target_de_de "Kanadisch 1801"
   Target_es_es "Canadiense 1801"
   Target_cs_cz "Kanadský 1801"
   Target_pl_pl "Kanadyjski 1801"
   Target_ru_ru "Канадский 1801"
   Target_ja_jp "カナダ1801年"
   Target_ko_kr "캐나다 1801"
   Target_pt_br "Canadense 1801"
   Target_zh_cn "加拿大 1801"
   Target_uk_ua "Канадський 1801"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334ACC78CB8}" {
   Id "Canadian1868"
   Target_en_us "Canadian 1868"
   Target_en_us_edited ""
   Target_fr_fr "Canadien 1868"
   Target_it_it "Canadese 1868"
   Target_de_de "Kanadisch 1868"
   Target_es_es "Canadiense 1868"
   Target_cs_cz "Kanadský 1868"
   Target_pl_pl "Kanadyjski 1868"
   Target_ru_ru "Канадский 1868"
   Target_ja_jp "カナダ1868年"
   Target_ko_kr "캐나다 1868"
   Target_pt_br "Canadense 1868"
   Target_zh_cn "加拿大 1868"
   Target_uk_ua "Канадський 1868"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334A72F7F82}" {
   Id "CapeColony1876"
   Target_en_us "Cape Colony 1876"
   Target_en_us_edited ""
   Target_fr_fr "Colonie du Cap 1876"
   Target_it_it "Colonia del Capo 1876"
   Target_de_de "Kapkolonie 1876"
   Target_es_es "Colonia del Cabo 1876"
   Target_cs_cz "Kapská kolonie 1876"
   Target_pl_pl "Kolonia Przylądkowa 1876"
   Target_ru_ru "Капская колония 1876"
   Target_ja_jp "ケープ植民地1876年"
   Target_ko_kr "케이프 식민지 1876년"
   Target_pt_br "Colônia do Cabo 1876"
   Target_zh_cn "好望角殖民地 1876"
   Target_uk_ua "Капська колонія 1876"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334AA095C1E}" {
   Id "CSA"
   Target_en_us "CSA"
   Target_en_us_edited ""
   Target_fr_fr "États confédérés"
   Target_it_it "Stati Confederati"
   Target_de_de "Konföderierte Staaten"
   Target_es_es "Estados Confederados"
   Target_cs_cz "Konfederace"
   Target_pl_pl "Konfederacja Stanów"
   Target_ru_ru "КША"
   Target_ja_jp "アメリカ連合国"
   Target_ko_kr "남부 연합"
   Target_pt_br "Estados Confederados"
   Target_zh_cn "美利坚联盟国"
   Target_uk_ua "Конфедеративні Штати"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334B68BAA25}" {
   Id "CSAArmy"
   Target_en_us "CSA Army"
   Target_en_us_edited ""
   Target_fr_fr "Armée des CSA"
   Target_it_it "Esercito CSA"
   Target_de_de "CSA Armee"
   Target_es_es "Ejército de la CSA"
   Target_cs_cz "Armáda CSA"
   Target_pl_pl "Armia CSA"
   Target_ru_ru "Армия КША"
   Target_ja_jp "CSA陸軍"
   Target_ko_kr "CSA 육군"
   Target_pt_br "Exército CSA"
   Target_zh_cn "美利坚联盟国陆军"
   Target_uk_ua "Армія КША"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334A92FF37F}" {
   Id "CSANavy"
   Target_en_us "CSA Navy"
   Target_en_us_edited ""
   Target_fr_fr "Marine des CSA"
   Target_it_it "Marina CSA"
   Target_de_de "CSA Marine"
   Target_es_es "Armada de la CSA"
   Target_cs_cz "Námořnictvo CSA"
   Target_pl_pl "Marynarka CSA"
   Target_ru_ru "ВМС КША"
   Target_ja_jp "CSA海軍"
   Target_ko_kr "CSA 해군"
   Target_pt_br "Marinha CSA"
   Target_zh_cn "美利坚联盟国海军"
   Target_uk_ua "ВМС КША"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD53349F03B64F}" {
   Id "EastIndiaCompany1801"
   Target_en_us "East India Company 1801"
   Target_en_us_edited ""
   Target_fr_fr "Compagnie des Indes orientales 1801"
   Target_it_it "Compagnia delle Indie orientali 1801"
   Target_de_de "Ostindische Kompanie 1801"
   Target_es_es "Compañía de las Indias Orientales 1801"
   Target_cs_cz "Východoindická společnost 1801"
   Target_pl_pl "Kompania Wschodnioindyjska 1801"
   Target_ru_ru "Ост-Индская компания 1801"
   Target_ja_jp "東インド会社1801年"
   Target_ko_kr "동인도 회사 1801년"
   Target_pt_br "Companhia das Índias Orientais 1801"
   Target_zh_cn "东印度公司 1801年"
   Target_uk_ua "Ост-Індійська компанія 1801"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD53305B3E8DD2}" {
   Id "Flag"
   Target_en_us "Flag"
   Target_en_us_edited ""
   Target_fr_fr "Drapeau"
   Target_it_it "Bandiera"
   Target_de_de "Flagge"
   Target_es_es "Bandera"
   Target_cs_cz "Vlajka"
   Target_pl_pl "Flaga"
   Target_ru_ru "Флаг"
   Target_ja_jp "旗 (はた)"
   Target_ko_kr "깃발"
   Target_pt_br "Bandeira"
   Target_zh_cn "旗帜"
   Target_uk_ua "Прапор"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334927A77CC}" {
   Id "France"
   Target_en_us "France"
   Target_en_us_edited ""
   Target_fr_fr "France"
   Target_it_it "Francia"
   Target_de_de "Frankreich"
   Target_es_es "Francia"
   Target_cs_cz "Francie"
   Target_pl_pl "Francja"
   Target_ru_ru "Франция"
   Target_ja_jp "フランス"
   Target_ko_kr "프랑스"
   Target_pt_br "França"
   Target_zh_cn "法国"
   Target_uk_ua "Франція"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD533491425847}" {
   Id "FrenchEmpire1801"
   Target_en_us "French Empire 1801"
   Target_en_us_edited ""
   Target_fr_fr "Empire français 1801"
   Target_it_it "Impero francese 1801"
   Target_de_de "Französisches Kaiserreich 1801"
   Target_es_es "Imperio francés 1801"
   Target_cs_cz "Francouzská říše 1801"
   Target_pl_pl "Cesarstwo Francuskie 1801"
   Target_ru_ru "Французская империя 1801"
   Target_ja_jp "フランス帝国1801年"
   Target_ko_kr "프랑스 제국 1801년"
   Target_pt_br "Império Francês 1801"
   Target_zh_cn "法兰西帝国 1801年"
   Target_uk_ua "Французька імперія 1801"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334946D0F73}" {
   Id "FrenchEmpire1870"
   Target_en_us "French Empire 1870"
   Target_en_us_edited ""
   Target_fr_fr "Empire français 1870"
   Target_it_it "Impero francese 1870"
   Target_de_de "Französisches Kaiserreich 1870"
   Target_es_es "Imperio francés 1870"
   Target_cs_cz "Francouzská říše 1870"
   Target_pl_pl "Cesarstwo Francuskie 1870"
   Target_ru_ru "Французская империя 1870"
   Target_ja_jp "フランス帝国1870年"
   Target_ko_kr "프랑스 제국 1870년"
   Target_pt_br "Império Francês 1870"
   Target_zh_cn "法兰西帝国 1870年"
   Target_uk_ua "Французька імперія 1870"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD53348B100623}" {
   Id "GermanEmpire1867"
   Target_en_us "German Empire 1867"
   Target_en_us_edited ""
   Target_fr_fr "Empire allemand 1867"
   Target_it_it "Impero tedesco 1867"
   Target_de_de "Deutsches Kaiserreich 1867"
   Target_es_es "Imperio alemán 1867"
   Target_cs_cz "Německá říše 1867"
   Target_pl_pl "Cesarstwo Niemieckie 1867"
   Target_ru_ru "Германская империя 1867"
   Target_ja_jp "ドイツ帝国1867年"
   Target_ko_kr "독일 제국 1867년"
   Target_pt_br "Império Alemão 1867"
   Target_zh_cn "德意志帝国 1867年"
   Target_uk_ua "Німецька імперія 1867"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD53348E7235F2}" {
   Id "GermanEmpireWar1867"
   Target_en_us "German Imperial War Flag 1867"
   Target_en_us_edited ""
   Target_fr_fr "Drapeau de guerre impérial allemand 1867"
   Target_it_it "Bandiera da guerra imperiale tedesca 1867"
   Target_de_de "Reichskriegsflagge 1867"
   Target_es_es "Bandera de guerra imperial alemana 1867"
   Target_cs_cz "Německá císařská válečná vlajka 1867"
   Target_pl_pl "Niemiecka cesarska flaga wojenna 1867"
   Target_ru_ru "Германский имперский военный флаг 1867"
   Target_ja_jp "ドイツ帝国戦闘旗1867年"
   Target_ko_kr "독일 제국 전쟁 깃발 1867년"
   Target_pt_br "Bandeira de guerra imperial alemã 1867"
   Target_zh_cn "德意志帝国战旗 1867年"
   Target_uk_ua "Німецький імперський військовий прапор 1867"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD533486FC6592}" {
   Id "GreatBritain"
   Target_en_us "Great Britain"
   Target_en_us_edited ""
   Target_fr_fr "Grande-Bretagne"
   Target_it_it "Gran Bretagna"
   Target_de_de "Großbritannien"
   Target_es_es "Gran Bretaña"
   Target_cs_cz "Velká Británie"
   Target_pl_pl "Wielka Brytania"
   Target_ru_ru "Великобритания"
   Target_ja_jp "イギリス"
   Target_ko_kr "영국"
   Target_pt_br "Grã-Bretanha"
   Target_zh_cn "大不列颠"
   Target_uk_ua "Велика Британія"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD53348CE380D5}" {
   Id "GreatBritain1701"
   Target_en_us "Great Britain 1701"
   Target_en_us_edited ""
   Target_fr_fr "Grande-Bretagne 1701"
   Target_it_it "Gran Bretagna 1701"
   Target_de_de "Großbritannien 1701"
   Target_es_es "Gran Bretaña 1701"
   Target_cs_cz "Velká Británie 1701"
   Target_pl_pl "Wielka Brytania 1701"
   Target_ru_ru "Великобритания 1701"
   Target_ja_jp "イギリス1701年"
   Target_ko_kr "영국 1701년"
   Target_pt_br "Grã-Bretanha 1701"
   Target_zh_cn "大不列颠 1701年"
   Target_uk_ua "Велика Британія 1701"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334833DF426}" {
   Id "GreatBritainArmy"
   Target_en_us "Great Britain Army"
   Target_en_us_edited ""
   Target_fr_fr "Armée de Grande-Bretagne"
   Target_it_it "Esercito di Gran Bretagna"
   Target_de_de "Britische Armee"
   Target_es_es "Ejército de Gran Bretaña"
   Target_cs_cz "Armáda Velké Británie"
   Target_pl_pl "Armia Wielkiej Brytanii"
   Target_ru_ru "Армия Великобритании"
   Target_ja_jp "イギリス軍"
   Target_ko_kr "영국 육군"
   Target_pt_br "Exército da Grã-Bretanha"
   Target_zh_cn "英国军队"
   Target_uk_ua "Армія Великобританії"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5331E95C3522}" {
   Id "GreatBritainNavy"
   Target_en_us "Great Britain Navy"
   Target_en_us_edited ""
   Target_fr_fr "Marine de Grande-Bretagne"
   Target_it_it "Marina di Gran Bretagna"
   Target_de_de "Britische Marine"
   Target_es_es "Armada de Gran Bretaña"
   Target_cs_cz "Námořnictvo Velké Británie"
   Target_pl_pl "Marynarka Wielkiej Brytanii"
   Target_ru_ru "ВМС Великобритании"
   Target_ja_jp "イギリス海軍"
   Target_ko_kr "영국 해군"
   Target_pt_br "Marinha da Grã-Bretanha"
   Target_zh_cn "英国海军"
   Target_uk_ua "ВМС Великобританії"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334FB1FB524}" {
   Id "KingdomofFrance1636"
   Target_en_us "Kingdom of France 1636"
   Target_en_us_edited ""
   Target_fr_fr "Royaume de France 1636"
   Target_it_it "Regno di Francia 1636"
   Target_de_de "Königreich Frankreich 1636"
   Target_es_es "Reino de Francia 1636"
   Target_cs_cz "Království Francie 1636"
   Target_pl_pl "Królestwo Francji 1636"
   Target_ru_ru "Королевство Франция 1636"
   Target_ja_jp "フランス王国1636年"
   Target_ko_kr "프랑스 왕국 1636년"
   Target_pt_br "Reino da França 1636"
   Target_zh_cn "法兰西王国 1636年"
   Target_uk_ua "Королівство Франції 1636"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334FE50F065}" {
   Id "KingdomofFrance1830"
   Target_en_us "Kingdom of France 1830"
   Target_en_us_edited ""
   Target_fr_fr "Royaume de France 1830"
   Target_it_it "Regno di Francia 1830"
   Target_de_de "Königreich Frankreich 1830"
   Target_es_es "Reino de Francia 1830"
   Target_cs_cz "Království Francie 1830"
   Target_pl_pl "Królestwo Francji 1830"
   Target_ru_ru "Королевство Франция 1830"
   Target_ja_jp "フランス王国1830年"
   Target_ko_kr "프랑스 왕국 1830년"
   Target_pt_br "Reino da França 1830"
   Target_zh_cn "法兰西王国 1830年"
   Target_uk_ua "Королівство Франції 1830"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334F5AC272B}" {
   Id "Prussia"
   Target_en_us "Prussia"
   Target_en_us_edited ""
   Target_fr_fr "Prusse"
   Target_it_it "Prussia"
   Target_de_de "Preußen"
   Target_es_es "Prusia"
   Target_cs_cz "Prusko"
   Target_pl_pl "Prusy"
   Target_ru_ru "Пруссия"
   Target_ja_jp "プロイセン"
   Target_ko_kr "프로이센"
   Target_pt_br "Prússia"
   Target_zh_cn "普鲁士"
   Target_uk_ua "Пруссія"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334F269C4B4}" {
   Id "PrussiaArmy1816"
   Target_en_us "Prussian Army 1816"
   Target_en_us_edited ""
   Target_fr_fr "Armée prussienne 1816"
   Target_it_it "Esercito prussiano 1816"
   Target_de_de "Preußische Armee 1816"
   Target_es_es "Ejército prusiano 1816"
   Target_cs_cz "Pruská armáda 1816"
   Target_pl_pl "Armia Pruska 1816"
   Target_ru_ru "Прусская армия 1816"
   Target_ja_jp "プロイセン陸軍1816年"
   Target_ko_kr "프로이센 육군 1816년"
   Target_pt_br "Exército prussiano 1816"
   Target_zh_cn "普鲁士陆军 1816年"
   Target_uk_ua "Прусська армія 1816"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334E0F5A1AD}" {
   Id "RussiaEmpire"
   Target_en_us "Russian Empire"
   Target_en_us_edited ""
   Target_fr_fr "Empire russe"
   Target_it_it "Impero russo"
   Target_de_de "Russisches Kaiserreich"
   Target_es_es "Imperio ruso"
   Target_cs_cz "Ruské impérium"
   Target_pl_pl "Imperium Rosyjskie"
   Target_ru_ru "Российская империя"
   Target_ja_jp "ロシア帝国"
   Target_ko_kr "러시아 제국"
   Target_pt_br "Império Russo"
   Target_zh_cn "俄罗斯帝国"
   Target_uk_ua "Російська імперія"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334ED09465D}" {
   Id "RussiaEmpire1858"
   Target_en_us "Russian Empire 1858"
   Target_en_us_edited ""
   Target_fr_fr "Empire russe 1858"
   Target_it_it "Impero russo 1858"
   Target_de_de "Russisches Kaiserreich 1858"
   Target_es_es "Imperio ruso 1858"
   Target_cs_cz "Ruské impérium 1858"
   Target_pl_pl "Imperium Rosyjskie 1858"
   Target_ru_ru "Российская империя 1858"
   Target_ja_jp "ロシア帝国1858年"
   Target_ko_kr "러시아 제국 1858년"
   Target_pt_br "Império Russo 1858"
   Target_zh_cn "俄罗斯帝国 1858年"
   Target_uk_ua "Російська імперія 1858"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334E7B49F17}" {
   Id "RussiaEmpireNavy"
   Target_en_us "Russian Empire Navy"
   Target_en_us_edited ""
   Target_fr_fr "Marine de l'Empire russe"
   Target_it_it "Marina dell'Impero russo"
   Target_de_de "Russische Marine"
   Target_es_es "Armada del Imperio Ruso"
   Target_cs_cz "Námořnictvo Ruského impéria"
   Target_pl_pl "Marynarka Imperium Rosyjskiego"
   Target_ru_ru "Военно-морской флот Российской империи"
   Target_ja_jp "ロシア帝国海軍"
   Target_ko_kr "러시아 제국 해군"
   Target_pt_br "Marinha do Império Russo"
   Target_zh_cn "俄罗斯帝国海军"
   Target_uk_ua "ВМС Російської імперії"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334DA9AB288}" {
   Id "US13Colony"
   Target_en_us "13 American colonies"
   Target_en_us_edited ""
   Target_fr_fr "13 colonies américaines"
   Target_it_it "13 colonie americane"
   Target_de_de "13 Kolonien der USA"
   Target_es_es "13 colonias de EE.UU."
   Target_cs_cz "13 kolonií USA"
   Target_pl_pl "13 kolonii USA"
   Target_ru_ru "13 колоний США"
   Target_ja_jp "13植民地"
   Target_ko_kr "13개 식민지"
   Target_pt_br "13 Colônias dos EUA"
   Target_zh_cn "美国13殖民地"
   Target_uk_ua "13 колоній США"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629211
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334DE2FE15D}" {
   Id "US1776"
   Target_en_us "US 1776"
   Target_en_us_edited ""
   Target_fr_fr "États-Unis 1776"
   Target_it_it "Stati Uniti 1776"
   Target_de_de "USA 1776"
   Target_es_es "EE.UU. 1776"
   Target_cs_cz "USA 1776"
   Target_pl_pl "USA 1776"
   Target_ru_ru "США 1776"
   Target_ja_jp "アメリカ1776年"
   Target_ko_kr "미국 1776년"
   Target_pt_br "EUA 1776"
   Target_zh_cn "美国1776年"
   Target_uk_ua "США 1776"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334DDF44A3D}" {
   Id "US1800s"
   Target_en_us "US 1800s"
   Target_en_us_edited ""
   Target_fr_fr "États-Unis XIXe siècle"
   Target_it_it "Stati Uniti 1800"
   Target_de_de "USA 1800er Jahre"
   Target_es_es "EE.UU. siglo XIX"
   Target_cs_cz "USA 19. století"
   Target_pl_pl "USA XIX wiek"
   Target_ru_ru "США XIX век"
   Target_ja_jp "アメリカ1800年代"
   Target_ko_kr "미국 1800년대"
   Target_pt_br "EUA 1800"
   Target_zh_cn "19世纪的美国"
   Target_uk_ua "США XIX століття"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{62CD5334D1FD9224}" {
   Id "US1861"
   Target_en_us "US 1861"
   Target_en_us_edited ""
   Target_fr_fr "États-Unis 1861"
   Target_it_it "Stati Uniti 1861"
   Target_de_de "USA 1861"
   Target_es_es "EE.UU. 1861"
   Target_cs_cz "USA 1861"
   Target_pl_pl "USA 1861"
   Target_ru_ru "США 1861"
   Target_ja_jp "アメリカ1861年"
   Target_ko_kr "미국 1861년"
   Target_pt_br "EUA 1861"
   Target_zh_cn "美国1861年"
   Target_uk_ua "США 1861"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1657629133
   Author "claud"
   LastChanged "claud"
   ImageLink ""
   Hidden 0
  }
 }
}